### ISSUE TITLE
可否增加一个日本的全测试项

### ISSUE THREAD

**Issue by DearTanker** [spiritLHLS/ecsspeed#3]
感谢作者做的这个非常实用的脚本，希望可以再增加一个日本speedtest节点的测试项目，对于预测中转效果会很有帮助。

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/ecsspeed/assets/103393591/c60b6be9-70d1-402b-b11f-f1d10c281d89)
18个左右的节点，有必要测么。。。

**Comment by DearTanker** [comment]
@spiritLHLS 有必要的，很多中转基本都是用的日本和香港，所以对预测中转效果会有很大的参考价值。

**Comment by spiritLHLS** [comment]
有空的时候我添加上 日本 和 新加坡 的全测试，暂时没空

**Comment by DearTanker** [comment]
谢谢，如果能再加上新加坡就更完美了。

对了，近期发现大陆移动节点好像只剩下一个 `25858` 北京移动了，Speedtest 那边搜索到，还有个 `54312` 的杭州移动，不知道是什么缘故。

**Comment by spiritLHLS** [comment]
> 谢谢，如果能再加上新加坡就更完美了。
> 
> 对了，近期发现大陆移动节点好像只剩下一个 `25858` 北京移动了，Speedtest 那边搜索到，还有个 `54312` 的杭州移动，不知道是什么缘故。

https://github.com/spiritLHLS/speedtest.net-CN-ID/blob/main/CN_Mobile.csv

有更新，每日更新会确保可用性

**Comment by spiritLHLS** [comment]
两个数据源的SG和JP的数据已加入每日推送，对应的测速脚本我下周有空加上对应分区测速

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/ecsspeed/commit/c9e11db0269e126ae2b84b5cb2453660e90fa8a5

已增加日本/新加坡全测选项

**Comment by DearTanker** [comment]
@spiritLHLS 感谢大佬，迫不及待的在几个不同的VPS上测试了一下，好像会在第18个报错，然后又重新开始测试。。
另外，对齐可能需要调整一下。
```
root@vultr-jp-tokyo:~# bash <(wget -qO- --no-check-certificate https://github.com/spiritLHLS/ecsspeed/raw/main/script/ecsspeed-net.sh)
Locale set to C.utf8
checking root
checking curl
checking wget
checking tar
checking CDN
CDN available, using CDN
checking speedtest
——————————————————————————————— ecsspeed-net —————————————————————————————————
             bash <(wget -qO- bash.spiritlhl.net/ecs-net)
             Repo：https://github.com/spiritLHLS/ecsspeed 
             节点更新: 2024/05/17  | 脚本更新: 2024/05/18 
——————————————————————————————————————————————————————————————————————————————
脚本当天运行次数:82，累计运行次数:15407
测速类型:
        1.三网测速(就近节点)    3.联通          6.香港          10.退出测速
        2.三网测速(所有节点)    4.电信          7.台湾
                                5.移动          8.日本
                                                9.新加坡
——————————————————————————————————————————————————————————————————————————————

请输入数字选择测速类型: 8
checking speedtest servers
——————————————————————————————————————————————————————————————————————————————
位置             上传速度        下载速度        延迟     丢包率
日本Fussa-shi    668.23 Mbps     375.73 Mbps     24.07    0.0%
日本Misawa       4054.65 Mbps    2182.04 Mbps    11.72    0.0%
日本Tsukuba      6308.48 Mbps    4098.45 Mbps    3.40     0.7%
日本Sagamihara   840.26 Mbps     181.94 Mbps     17.60    0.0%
高知KingsBroadband       405.74 Mbps     934.50 Mbps     140.26   0.0%
高知Jio          525.61 Mbps     1268.75 Mbps    288.39   NULL
日本Naha         2944.43 Mbps    1809.09 Mbps    27.64    0.0%
东京i3D          301.07 Mbps     4856.15 Mbps    0.91     78.6%
"东京RakutenMobile       4714.20 Mbps    3888.98 Mbps    2.72     0.0%
高知DensLtd      394.48 Mbps     939.64 Mbps     151.33   3.3%
冲绳AlliedTelesis        2895.87 Mbps    2551.11 Mbps    27.92    0.0%
东京IPACyberLab400G      7415.30 Mbps    5393.89 Mbps    1.47     0.0%
东京Verizon      655.34 Mbps     133.53 Mbps     55.75    0.0%
东京Contabo      4580.85 Mbps    1192.19 Mbps    6.25     0.7%
东京サーバーならDDPS     5808.15 Mbps    4778.01 Mbps    1.22     0.0%
东京ChinaUnicom  657.68 Mbps     208.10 Mbps     1.96     0.4%
东京CTCSCITECHLTD        3934.42 Mbps    1271.37 Mbps    23.02    1.0%
grep: ./speedtest-cli/speedlog.txt: No such file or directory
Unable to use the 1.2.0, back to 1.0.0
checking speedtest servers
——————————————————————————————————————————————————————————————————————————————
位置             上传速度        下载速度        延迟     丢包率
日本Fussa-shi    422.59 Mbps     252.22 Mbps     19.00    0.0%
日本Misawa       4060.36 Mbps    2878.94 Mbps    9.95     0.0%

```

**Comment by spiritLHLS** [comment]
> @spiritLHLS 感谢大佬，迫不及待的在几个不同的VPS上测试了一下，好像会在第18个报错，然后又重新开始测试。。 另外，对齐可能需要调整一下。
> 
> ```
> root@vultr-jp-tokyo:~# bash <(wget -qO- --no-check-certificate https://github.com/spiritLHLS/ecsspeed/raw/main/script/ecsspeed-net.sh)
> Locale set to C.utf8
> checking root
> checking curl
> checking wget
> checking tar
> checking CDN
> CDN available, using CDN
> checking speedtest
> ——————————————————————————————— ecsspeed-net —————————————————————————————————
>              bash <(wget -qO- bash.spiritlhl.net/ecs-net)
>              Repo：https://github.com/spiritLHLS/ecsspeed 
>              节点更新: 2024/05/17  | 脚本更新: 2024/05/18 
> ——————————————————————————————————————————————————————————————————————————————
> 脚本当天运行次数:82，累计运行次数:15407
> 测速类型:
>         1.三网测速(就近节点)    3.联通          6.香港          10.退出测速
>         2.三网测速(所有节点)    4.电信          7.台湾
>                                 5.移动          8.日本
>                                                 9.新加坡
> ——————————————————————————————————————————————————————————————————————————————
> 
> 请输入数字选择测速类型: 8
> checking speedtest servers
> ——————————————————————————————————————————————————————————————————————————————
> 位置             上传速度        下载速度        延迟     丢包率
> 日本Fussa-shi    668.23 Mbps     375.73 Mbps     24.07    0.0%
> 日本Misawa       4054.65 Mbps    2182.04 Mbps    11.72    0.0%
> 日本Tsukuba      6308.48 Mbps    4098.45 Mbps    3.40     0.7%
> 日本Sagamihara   840.26 Mbps     181.94 Mbps     17.60    0.0%
> 高知KingsBroadband       405.74 Mbps     934.50 Mbps     140.26   0.0%
> 高知Jio          525.61 Mbps     1268.75 Mbps    288.39   NULL
> 日本Naha         2944.43 Mbps    1809.09 Mbps    27.64    0.0%
> 东京i3D          301.07 Mbps     4856.15 Mbps    0.91     78.6%
> "东京RakutenMobile       4714.20 Mbps    3888.98 Mbps    2.72     0.0%
> 高知DensLtd      394.48 Mbps     939.64 Mbps     151.33   3.3%
> 冲绳AlliedTelesis        2895.87 Mbps    2551.11 Mbps    27.92    0.0%
> 东京IPACyberLab400G      7415.30 Mbps    5393.89 Mbps    1.47     0.0%
> 东京Verizon      655.34 Mbps     133.53 Mbps     55.75    0.0%
> 东京Contabo      4580.85 Mbps    1192.19 Mbps    6.25     0.7%
> 东京サーバーならDDPS     5808.15 Mbps    4778.01 Mbps    1.22     0.0%
> 东京ChinaUnicom  657.68 Mbps     208.10 Mbps     1.96     0.4%
> 东京CTCSCITECHLTD        3934.42 Mbps    1271.37 Mbps    23.02    1.0%
> grep: ./speedtest-cli/speedlog.txt: No such file or directory
> Unable to use the 1.2.0, back to 1.0.0
> checking speedtest servers
> ——————————————————————————————————————————————————————————————————————————————
> 位置             上传速度        下载速度        延迟     丢包率
> 日本Fussa-shi    422.59 Mbps     252.22 Mbps     19.00    0.0%
> 日本Misawa       4060.36 Mbps    2878.94 Mbps    9.95     0.0%
> ```

修了，错误判断替换时忘了先判断日志文件在不在了
